CERTIFICATE_PATH			=${PWD}/Certificate
CERTIFICATE_NAME     		=connect4
RSA_LENGTH					=2048
DAYS						=365

CONNECT4_DAEMON_PORT		=7878
CONNECT4_DAEMON_PATH		=${PWD}/connect4Daemon
CONNECT4_DAEMON_BIN_NAME	=connect4_d
CONNECT4_DAEMON_HOST		=127.0.0.1

CONNECT4_CLIENT_PATH		=${PWD}/connect4
CONNECT4_CLIENT_NAME		=app:connect4

CERTIFICATE 				=$(addprefix $(CERTIFICATE_PATH)/, $(CERTIFICATE_NAME))
CONNECT4_DAEMON				=$(addprefix $(CONNECT4_DAEMON_PATH)/, $(CONNECT4_DAEMON_BIN_NAME))
CERTIFICATE_FILE_NAME		=$(addprefix $(CERTIFICATE),.pem)

CONNECT4_CLIENT_VENDOR		=$(addprefix $(CONNECT4_CLIENT_PATH)/,vendor)
CONNECT4_CLIENT_VAR			=$(addprefix $(CONNECT4_CLIENT_PATH)/,var)

$(CERTIFICATE_FILE_NAME): $(CERTIFICATE_PATH)
	openssl req \
		-newkey rsa:$(RSA_LENGTH) \
		-nodes \
		-keyout $(CERTIFICATE).key \
		-x509 \
		-days $(DAYS) \
		-out $(CERTIFICATE).crt
	cat $(CERTIFICATE).crt \
		$(CERTIFICATE).key \
		> $(CERTIFICATE_FILE_NAME)
	rm $(CERTIFICATE).crt \
		$(CERTIFICATE).key

$(CERTIFICATE_PATH):
	mkdir $(CERTIFICATE_PATH)

$(CONNECT4_DAEMON):
	make -C $(CONNECT4_DAEMON_PATH)

$(CONNECT4_CLIENT_VAR) : $(CONNECT4_CLIENT_VENDOR)

$(CONNECT4_CLIENT_VENDOR):
	composer update -d $(CONNECT4_CLIENT_PATH)
	composer install -d $(CONNECT4_CLIENT_PATH)

install: $(CERTIFICATE_FILE_NAME) $(CONNECT4_DAEMON) $(CONNECT4_CLIENT_VENDOR) $(CONNECT4_CLIENT_VAR)

run_server: $(CERTIFICATE_FILE_NAME) $(CONNECT4_DAEMON)
	$(CONNECT4_DAEMON) $(CONNECT4_DAEMON_PORT) $(CERTIFICATE_FILE_NAME)

run_client:$(CERTIFICATE_FILE_NAME) $(CONNECT4_CLIENT_VENDOR) $(CONNECT4_CLIENT_VAR)
	php $(CONNECT4_CLIENT_PATH)/bin/console $(CONNECT4_CLIENT_NAME) $(CONNECT4_DAEMON_HOST) $(CONNECT4_DAEMON_PORT) $(CERTIFICATE_FILE_NAME)

fclean:
	rm -rf $(CONNECT4_CLIENT_VAR) 
	rm -rf $(CONNECT4_CLIENT_VENDOR)
	rm -rf $(CERTIFICATE_PATH)
	make fclean -C $(CONNECT4_DAEMON_PATH)

.phony:
	run_server run_client fclean install